apiVersion: apps/v1
kind: Deployment
metadata:
  name: train-deploy
  labels:
    app: train-schedule
spec:
  replicas: 3
  selector:
    matchLabels:
      app: train-schedule
  template:
    metadata:
      labels:
        app: train-schedule
    spec:
      containers:
      - name: train-schedule-container
        image: $DOCKER_IMAGE_NAME:$BUILD_NUMBER
        ports:
        - containerPort: 8080
---
apiVersion: v1
kind: Service
metadata:
  name: train-np-service
  labels:
    app: train-schedule
spec:
  selector:
    app: train-schedule

  type: NodePort
  ports:
  - nodePort: 31000
    port: 8080
    targetPort: 8080
