#Service Type nodePort
apiVersion: v1
kind: Service
metadata:
  name: train-np-service
  labels:
    app: train-schedule
spec:
  selector:
    app: train-schedule

  type: NodePort
  ports:
  - nodePort: 31000
    port: 8080
    targetPort: 8080
